### ISSUE TITLE
Concurrent Executions Apply Schema Version Twice

### ISSUE THREAD

**Issue by casba** [Snowflake-Labs/schemachange#128] opened 2022-09-21 13:53 UTC
Hi,

We unintentionally ran the schemachange command in two separate Jenkins pipelines concurrently, and were surprised to see that each pipeline successfully applied the latest version of our schema. This generated two rows in the change_history table with duplicate contents, save for the timestamp. Is there any way to protect against concurrent execution using this tool? Looking closer at snowflakes supported SQL commands, it's not clear to me that it would be possible.

**Comment by CermitDFrog** [comment] 2022-09-23 01:50
Reads don't block in Snowflake and schemachange reads the current change state early in the execution chain. This is the exact behavior I would expect.

**Comment by sfc-gh-tmathew** [comment] 2023-09-26 04:53
Hello @casba 

Thank you for reaching out. As @CermitDFrog pointed out, Schemachange is behaving as designed. 

I cannot think of a way to block a client connection from executing a SQL statement because another connection is connected and executing a SQL statement on the same target database. 

Closing the issue because we will not be able to fix it.

**Closed by sfc-gh-tmathew** 2023-09-26 04:53 UTC
Labels: wontfix
