### ISSUE TITLE
SQL Syntax error when Snowflake role name includes special characters such as hyphens

### ISSUE THREAD

**Issue by jonathancisneros** [Snowflake-Labs/schemachange#215] opened 2024-01-02 19:52 UTC
The **USE ROLE** and the other USE query template strings here:
https://github.com/Snowflake-Labs/schemachange/blob/master/schemachange/cli.py#L213

are not using quoted values for the placeholder values, if there are special characters in the name of those values, the execution of the **reset_session** function fails with SQL compilation or syntax error.

please update the USE xxx template strings to support special characters by using quoted values like this:
_q_set_sess_role = 'USE ROLE "{role}";'

**Comment by dwelden** [comment] 2024-02-01 21:48
Duplicate of #186?

**Comment by sfc-gh-tmathew** [comment] 2024-07-22 14:25
Thank you for highlighting this gap @dwelden @jonathancisneros 

Just released 3.7.0 that addressed roles with special characters. Please test it out and let us know if this issue can be closed.

**Comment by dwelden** [comment] 2024-08-01 14:32
This issue is resolved.

**Comment by sfc-gh-tmathew** [comment] 2024-08-05 18:16
Thank you @dwelden for confirming. Closing this issue for now.

**Closed by sfc-gh-tmathew** 2024-08-05 18:16 UTC
Labels: bug
