### ISSUE TITLE
undo or rollback to specific version

### ISSUE THREAD

**Issue by MallikarjunGattupally** [Snowflake-Labs/schemachange#160] opened 2023-02-24 10:54 UTC
Hello,
How can I undo or rollback to a specific version again in schemachange. What is the command for it ?

**Comment by CermitDFrog** [comment] 2023-02-24 13:02
There is not a indo or rollback built into schema change.

**Comment by afeld** [comment] 2023-06-20 21:44
Duplicate of https://github.com/Snowflake-Labs/schemachange/issues/19.

**Closed** 2023-06-22 07:27 UTC
